### PR TITLE
Minor improvements.

### PR DESCRIPTION
**Pull request by amalmurali47**

### CODE REVIEW

**Comment by amarlearning** [comment]
@amalmurali47 everything LGTM :+1: 
Thanks!

**Comment by amalmurali47** [comment]
@amarlearning: Cool. I couldn't really find anything that I could improve upon. Except maybe abstracting away all the database connection details into a different config file in JSON or something. Thoughts?

**Comment by amarlearning** [comment]
@amalmurali47 well we can do that!
But this leaves a negligible impact on feature and Performance.

I have some ideas to implement, but I don't have time. If you want I can help you in this.

**Comment by amalmurali47** [comment]
Sure. What are the ideas?

**Comment by amarlearning** [comment]
@amalmurali47 cool :+1: 

1. Instead of shortening a single there should an extended feature to shorten multiple URLs in a single click.
2. URL analytics.

Let me know if you need any help!

**Pull request merged**
